//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityUserRoles
    {
        public string UserId { get; set; }
        public string RoleId { get; set; }
        public string IdentityRole_Id { get; set; }
        public string ApplicationUser_Id { get; set; }
    
        public virtual ApplicationUsers ApplicationUsers { get; set; }
        public virtual IdentityRoles IdentityRoles { get; set; }
    }
}
