//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KaangKunShopEntities : DbContext
    {
        public KaangKunShopEntities()
            : base("name=KaangKunShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ApplicationUsers> ApplicationUsers { get; set; }
        public virtual DbSet<Errors> Errors { get; set; }
        public virtual DbSet<Footers> Footers { get; set; }
        public virtual DbSet<IdentityRoles> IdentityRoles { get; set; }
        public virtual DbSet<IdentityUserClaims> IdentityUserClaims { get; set; }
        public virtual DbSet<IdentityUserLogins> IdentityUserLogins { get; set; }
        public virtual DbSet<IdentityUserRoles> IdentityUserRoles { get; set; }
        public virtual DbSet<MenuGroups> MenuGroups { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Pages> Pages { get; set; }
        public virtual DbSet<PostCategories> PostCategories { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<ProductCategories> ProductCategories { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Slides> Slides { get; set; }
        public virtual DbSet<SupportOnlines> SupportOnlines { get; set; }
        public virtual DbSet<SystemConfigs> SystemConfigs { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<VisitorStatistics> VisitorStatistics { get; set; }
    }
}
